FROM jupyter/minimal-notebook:latest

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends default-jdk && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    pyspark==3.5.0 \
    boto3 \
    pandas

USER jovyan

CMD ["start-notebook.py", "--NotebookApp.token=jupyter"]
